import { readFile, writeFile } from "node:fs/promises";
const path="dist/index.html";
let h=await readFile(path,"utf8");
const one=(a,b,n)=>{const x=h;h=h.replace(a,b);if(h===x)throw Error("patch failed: "+n)};
const all=(a,b,n)=>{const x=h;h=h.replace(a,b);if(h===x)throw Error("patch failed: "+n)};

one(/<div class="home-settings">[\s\S]*?<\/div><\/div>\s*<div class="choice-grid">/,
`<div class="home-settings"><div class="home-settings-title">主持人建立房間前，設定隊伍與人數</div><div class="room-config-grid"><label class="room-config-field"><span>隊伍數</span><select id="teamCountSelect"><option value="2">2 隊</option><option value="3" selected>3 隊</option><option value="4">4 隊</option><option value="5">5 隊</option></select></label><label class="room-config-field"><span>每隊人數</span><select id="groupSizeSelect"><option value="2">2 人</option><option value="3">3 人</option><option value="4" selected>4 人</option><option value="5">5 人</option></select></label></div><div id="roomConfigSummary" class="room-config-summary">3 隊 × 每隊 4 人＝共 12 人</div></div><div class="choice-grid">`,"config ui");
one(/<\/style>/,`.room-config-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.room-config-field{display:flex;flex-direction:column;gap:7px;text-align:left;font-weight:900;color:#41483f}.room-config-field select{width:100%;padding:13px 14px;border:2px solid #e0e4dd;border-radius:14px;background:#fff;color:#343a32;font-weight:900;outline:none}.room-config-field select:focus{border-color:var(--sinyi-green);box-shadow:0 0 0 4px rgba(87,166,58,.09)}.room-config-summary{margin-top:12px;padding:10px 12px;border-radius:12px;background:var(--sinyi-green-soft);color:var(--sinyi-green-dark);font-weight:950;text-align:center}.three-grid,.team-grid,.final-team-groups{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))!important}@media(max-width:640px){.room-config-grid{grid-template-columns:1fr}.three-grid,.team-grid,.final-team-groups{grid-template-columns:1fr!important}}</style>`,"css");
h=h.replaceAll("30 分鐘・三組協作・六關挑戰","30 分鐘・多隊協作・六關挑戰").replaceAll("只有分享、推理、分工與同步，三組才能一起完成全員解鎖。","只有分享、推理、分工與同步，各隊才能一起完成全員解鎖。").replaceAll("使用電腦滿版投影、控制六關、倒數計時與查看三組進度。","使用電腦滿版投影、控制六關、倒數計時與查看各隊進度。").replaceAll("系統會自動平均分成三組。","系統會依主持人設定，自動平均分組。").replaceAll("<h3>三組參與名單</h3>","<h3>各隊參與名單</h3>").replaceAll("三組集合，準備連線","各隊集合，準備連線").replaceAll("三組必須把所有線索放在一起","各組必須把所有線索放在一起").replaceAll("三組都成功後再進下一關","各組都成功後再進下一關").replaceAll("接下來三組會一起完成六個關卡","接下來各隊會一起完成六個關卡");

one(/const TEAMS=\[[^\n]*\];/,`const TEAMS=[{id:"A",name:"紅屋組",color:"#e60012",tagline:"把方向說清楚"},{id:"B",name:"綠芽組",color:"#009b4c",tagline:"讓合作長出成果"},{id:"C",name:"暖光組",color:"#b78b35",tagline:"主動照亮與補位"},{id:"D",name:"藍海組",color:"#2b6cb0",tagline:"讓資訊流動起來"},{id:"E",name:"紫星組",color:"#7c3aed",tagline:"把不同觀點連起來"}];`,"teams");
one(/const PROCESS_TOKENS=\{[\s\S]*?const DEMO_NAMES=/,`const PROCESS_TOKENS={A:["7","2","9","4","6"],B:["3","8","1","5","0"],C:["6","4","8","2","9"],D:["5","1","7","3","8"],E:["9","6","2","8","4"]};
  function teamIndex(id){return Math.max(0,TEAMS.findIndex(t=>t.id===id))}
  function activeTeams(meta=appState?.room?.meta||{}){return TEAMS.slice(0,Math.max(2,Math.min(5,Number(meta.teamCount||3))))}
  function processOrder(id,size){const n=Math.max(2,Math.min(5,Number(size||4))),s=teamIndex(id)%n;return Array.from({length:n},(_,i)=>(i+s)%n)}
  function logicCode(id,size){const n=Math.max(2,Math.min(5,Number(size||4))),t=teamIndex(id);return Array.from({length:n},(_,i)=>String(((t+2)*3+i*2+n)%9+1)).join("")}
  function logicClue(id,seat,size){const c=logicCode(id,size),i=Math.max(0,Math.min(c.length-1,Number(seat||0))),d=Number(c[i]),a=Math.floor(d/2),o=["第一","第二","第三","第四","第五"];return \`\${o[i]}碼＝\${a}＋\${d-a}。\`}
  const DEMO_NAMES=`,"challenge data");

one(/  function baseRoom\(code,groupSize\)\{[^\n]*\}/,`  function baseRoom(code,groupSize,teamCount=3){const count=Math.max(2,Math.min(5,Number(teamCount||3))),size=Math.max(2,Math.min(5,Number(groupSize||4))),teams=TEAMS.slice(0,count),relay={},sequenceSolved={},sequenceAttempts={},logicSolved={},logicAttempts={};teams.forEach(t=>{relay[t.id]={next:1,status:"idle",attempts:0};sequenceSolved[t.id]=false;sequenceAttempts[t.id]=0;logicSolved[t.id]=false;logicAttempts[t.id]=0});return{meta:{code,stage:0,groupSize:size,teamCount:count,expected:size*count,createdAt:Date.now(),nextJoinIndex:0,timerRunning:false,timerStartedAt:0,timerRemainingSec:stageDuration(0),sequenceSolved,sequenceAttempts,logicSolved,logicAttempts,relay,syncRound:0,syncStartedAt:0,syncStatus:"idle",syncWins:0,syncResolvedRound:0},players:{}}}`,"base room");
one(/  async function createHostRoom\(\)\{[^\n]*\}/,`  async function createHostRoom(){const size=Math.max(2,Math.min(5,Number($("groupSizeSelect")?.value||4))),teamCount=Math.max(2,Math.min(5,Number($("teamCountSelect")?.value||3)));let code=randomRoom();for(let i=0;i<6&&await appState.backend.exists(code);i++)code=randomRoom();await appState.backend.createRoom(code,baseRoom(code,size,teamCount));appState.mode="host";appState.roomCode=code;sessionStorage.setItem("landing_team_host_room_30",code);await subscribeRoom(code);showView("hostView")}`,"create room");
one(/  async function joinRoom\(\)\{[^\n]*\}/,`  async function joinRoom(){const code=$("joinRoomInput").value.trim(),name=$("joinNameInput").value.trim();if(!/^\\d{4}$/.test(code))return toast("請輸入四位房號");if(!name)return toast("請輸入姓名");if(!(await appState.backend.exists(code)))return toast("找不到房間");const room=await appState.backend.getRoom(code),max=Number(room.meta.expected),teamCount=Math.max(2,Math.min(5,Number(room.meta.teamCount||3))),idx=await appState.backend.claimJoinIndex(code,max);if(idx<0)return toast("房間已滿");const ti=idx%teamCount,seat=Math.floor(idx/teamCount),team=TEAMS[ti],id=uid(),p={id,name,joinIndex:idx,joinedAt:Date.now(),teamId:team.id,seatIndex:seat,relayOrder:seat+1,roleChoice:"",supportChoice:"",sequenceShared:false,logicShared:false,relaySolved:false,commitmentValue:"",message:"",syncRoundPressed:0,isDemo:false};await appState.backend.setPath(code,\`players/\${id}\`,p);appState.mode="player";appState.roomCode=code;appState.playerId=id;sessionStorage.setItem("landing_team_player_30",JSON.stringify({code,id}));await subscribeRoom(code);showView("playerView")}`,"join");
one(/  async function setStage\(stage\)\{[^\n]*\}/,`  async function setStage(stage){const safe=Math.max(0,Math.min(STAGES.length-1,stage)),relay={};activeTeams(appState.room?.meta).forEach(t=>relay[t.id]={next:1,status:"idle",attempts:0});const u={"meta/stage":safe,"meta/timerRunning":false,"meta/timerStartedAt":0,"meta/timerRemainingSec":stageDuration(safe)};if(safe!==5)u["meta/syncStatus"]="idle";await appState.backend.update(appState.roomCode,u)}`,"stage");
one(/  function processAnswer\(teamId,size\)\{[^\n]*\}\n  function processCard\(p,size\)\{[^\n]*\}\n  function relayQuestion\(p,size\)\{[^\n]*\}/,`  function processAnswer(teamId,size){return PROCESS_TOKENS[teamId].slice(0,size).join("")}
  function processCard(p,size){const order=processOrder(p.teamId,size)[p.seatIndex]??0;return{step:PROCESS_STEPS[order],token:PROCESS_TOKENS[p.teamId][order],order}}
  function relayQuestion(p,size){const tc=Math.max(2,Math.min(5,Number(appState.room?.meta?.teamCount||3))),expected=size*tc,bank=[["2、4、8、16、？","32"],[\`\${expected} 人平均分成 \${tc} 組，每組幾人？\`,String(size)],["SINYI 中有幾個不同英文字母？","4"],["12 分鐘分成 4 等份，每份幾分鐘？","3"],[\`\${tc} 組各 \${size} 人，再加主持人共幾人？\`,String(expected+1)]],q=bank[(Number(p.seatIndex||0)+teamIndex(p.teamId))%bank.length];return{question:q[0],answer:q[1]}}`,"challenge helpers");

all(/TEAMS\.map\(t=>/g,"activeTeams(m).map(t=>","maps");
all(/TEAMS\.flatMap\(t=>/g,"activeTeams(m).flatMap(t=>","flatmap");
all(/LOGIC_CODES\[size\]\[t\.id\]/g,"logicCode(t.id,size)","logic host");
all(/LOGIC_CLUES\[p\.teamId\]\[p\.seatIndex\]/g,"logicClue(p.teamId,p.seatIndex,size)","logic clue");
all(/LOGIC_CODES\[size\]\[p\.teamId\]/g,"logicCode(p.teamId,size)","logic answer");
one(/const size=Number\(m\.groupSize\|\|4\), expected=Number\(m\.expected\|\|size\*3\);/,`const size=Number(m.groupSize||4), teamCount=Number(m.teamCount||3), expected=Number(m.expected||size*teamCount);`,"guide count");

one(/  async function fillDemoPlayers\(\)\{[^\n]*\}/,`  async function fillDemoPlayers(){const m=appState.room.meta,u={},tc=Math.max(2,Math.min(5,Number(m.teamCount||3)));for(let i=getPlayers().length;i<m.expected;i++){const id=\`demo_\${String(i+1).padStart(2,"0")}\`,ti=i%tc,seat=Math.floor(i/tc);u[\`players/\${id}\`]={id,name:DEMO_NAMES[i]||\`夥伴\${i+1}\`,joinIndex:i,joinedAt:Date.now()+i,teamId:TEAMS[ti].id,seatIndex:seat,relayOrder:seat+1,roleChoice:"",supportChoice:"",sequenceShared:false,logicShared:false,relaySolved:false,commitmentValue:"",message:"",syncRoundPressed:0,isDemo:true}}u["meta/nextJoinIndex"]=m.expected;await appState.backend.update(appState.roomCode,u);toast("測試成員已加入")}`,"demo fill");
one(/  async function demoSequence\(\)\{[^\n]*\}/,`  async function demoSequence(){const u={};activeTeams(appState.room.meta).forEach((t,i)=>{u[\`meta/sequenceSolved/\${t.id}\`]=true;u[\`meta/sequenceAttempts/\${t.id}\`]=i%2+1});getPlayers().filter(p=>p.isDemo).forEach(p=>u[\`players/\${p.id}/sequenceShared\`]=true);await appState.backend.update(appState.roomCode,u)}`,"demo seq");
one(/  async function demoLogic\(\)\{[^\n]*\}/,`  async function demoLogic(){const u={};activeTeams(appState.room.meta).forEach((t,i)=>{u[\`meta/logicSolved/\${t.id}\`]=true;u[\`meta/logicAttempts/\${t.id}\`]=i%2+1});getPlayers().filter(p=>p.isDemo).forEach(p=>u[\`players/\${p.id}/logicShared\`]=true);await appState.backend.update(appState.roomCode,u)}`,"demo logic");
one(/  async function demoRelay\(\)\{[^\n]*\}/,`  async function demoRelay(){const u={};getPlayers().filter(p=>p.isDemo).forEach(p=>u[\`players/\${p.id}/relaySolved\`]=true);activeTeams(appState.room.meta).forEach((t,i)=>u[\`meta/relay/\${t.id}\`]={next:Number(appState.room.meta.groupSize)+1,status:"success",attempts:i===1?1:0});await appState.backend.update(appState.roomCode,u)}`,"demo relay");
one(/  async function resetRoom\(\)\{[^\n]*\}/,`  async function resetRoom(){if(!confirm("確定清除全部成員與六關進度？"))return;const size=Number(appState.room.meta.groupSize||4),tc=Number(appState.room.meta.teamCount||3);await appState.backend.createRoom(appState.roomCode,baseRoom(appState.roomCode,size,tc));toast("房間已重設")}`,"reset");
one(/\$\("chooseHost"\)\.addEventListener\("click",createHostRoom\);/,`function updateRoomConfigSummary(){const t=Number($("teamCountSelect")?.value||3),s=Number($("groupSizeSelect")?.value||4),e=$("roomConfigSummary");if(e)e.textContent=\`\${t} 隊 × 每隊 \${s} 人＝共 \${t*s} 人\`}[$("teamCountSelect"),$("groupSizeSelect")].forEach(e=>e?.addEventListener("change",updateRoomConfigSummary));updateRoomConfigSummary();$("chooseHost").addEventListener("click",createHostRoom);`,"summary");

await writeFile(path,h,"utf8");
console.log("Applied configurable team settings");
